services:
  marreta:
    container_name: marreta
    image: ghcr.io/manualdousuario/marreta:latest
    ports:
      - "81:8080"
    volumes:
      - marreta_storage:/var/www/html/storage/app
    environment:
      - APP_NAME=${APP_NAME:-Marreta}
      - APP_KEY=${APP_KEY:-} # https://laravel-encryption-key-generator.vercel.app
      - APP_DEBUG=${APP_DEBUG:-false}
      - APP_URL=${APP_URL:-http://localhost:81}
      - APP_LOCALE=${APP_LOCALE:-pt-br}
      - APP_DESCRIPTION=${APP_DESCRIPTION:-Chapéu de paywall é marreta!}
      - BROWSER_WS_ENDPOINT=${BROWSER_WS_ENDPOINT:-ws://marreta_browser:9222}
      - PROXY_URL=${PROXY_URL:-}
      - DISABLE_CACHE=${DISABLE_CACHE:-false}
      - ADMIN_EMAIL=${ADMIN_EMAIL:-admin@marreta.local}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:?defina ADMIN_PASSWORD}
    depends_on:
      - marreta_browser
    restart: unless-stopped

  marreta_browser:
    container_name: marreta_browser
    image: lightpanda/browser:nightly
    restart: unless-stopped

volumes:
  marreta_storage:
