services:
  marreta:
    container_name: marreta
    image: ghcr.io/manualdousuario/marreta:latest
    ports:
      - "80:80"
    volumes:
      - ./app/cache:/app/cache
      - ./app/logs:/app/logs
    environment:
      - SITE_NAME=${SITE_NAME:-}
      - SITE_DESCRIPTION=${SITE_DESCRIPTION:-}
      - SITE_URL=${SITE_URL:-}
      - DNS_SERVERS=${DNS_SERVERS:-}
    # Add user mapping to help with permissions
    user: "${UID:-1000}:${GID:-1000}"
    restart: unless-stopped
