services:
  marreta:
    container_name: marreta
    image: ghcr.io/manualdousuario/marreta:latest
    ports:
      - "80:80"
    volumes:
      - ./app/cache:/app/cache
      - ./app/logs:/app/logs
    environment:
      # Configurações básicas
      - SITE_NAME=${SITE_NAME:-}
      - SITE_DESCRIPTION=${SITE_DESCRIPTION:-}
      - SITE_URL=${SITE_URL:-}
      - DNS_SERVERS=${DNS_SERVERS:-}
      # Configurações de Cache S3 (opcional)
      - S3_CACHE_ENABLED=${S3_CACHE_ENABLED:-false}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY:-}
      - S3_SECRET_KEY=${S3_SECRET_KEY:-}
      - S3_BUCKET=${S3_BUCKET:-}
      - S3_REGION=${S3_REGION:-us-east-1}
      - S3_FOLDER=${S3_FOLDER:-cache/}
      - S3_ACL=${S3_ACL:-private}
      - S3_ENDPOINT=${S3_ENDPOINT:-}
    user: "${UID:-1000}:${GID:-1000}"
    restart: unless-stopped
